### ISSUE TITLE
[Question]: What is the policy on adding new models to this repository

### ISSUE THREAD

**Issue by himankpathak** [TabbyML/registry-tabby#19]
### Description
Hi, I wanted to use `Qwen/Qwen2.5-3B-Instruct` as a chat model after the v0.19 release. But unfortunately, this 3B one was not added to the registry. I'm checking if it's fair to open PR to add a model to this repository?

I am aware that downloading the model locally and setting it up according to [MODEL_SPEC](https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md) is possible. This involves a lot of manual work, like downloading the model, creating the .json file, and dealing with permission issues with `.tabby/` to move it to the correct location.
I was wondering if it is possible to pass a GGUF URL to the `serve` command to leverage the already existing code to download and set up the desired model automatically. This would be very impressive.

**Comment by wsxiaoys** [comment]
The short answer is that only the models we have tested and benchmarked will be added to the registry.

If you wish to use your own model in a registry, please refer to https://github.com/wsxiaoys/registry-tabby. You can create a fork and then set up your model accordingly. Your model can then be accessed using `your-fork-handle/model-name`.

**Comment by himankpathak** [comment]
Thank you @wsxiaoys for your insightful suggestion. 
I was able to add the model I need to [my fork](https://github.com/himankpathak/registry-tabby) and use it simply by passing `fork/model-name` to the serve command. 

This is exactly what I needed! 🚀
